services:
  floci:
    container_name: cloud-vault-floci
    image: ${FLOCI_IMAGE:-floci/floci:2.1.0}
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - FLOCI_STORAGE_MODE=persistent
      - FLOCI_DEFAULT_REGION=us-east-1
      - FLOCI_DOCKER_DOCKER_HOST=unix:///var/run/docker.sock
      - FLOCI_RUN_AS_ROOT=true
    volumes:
      - "${FLOCI_VOLUME_DIR:-./.floci}:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
